### ISSUE TITLE
Internal functions should be placed towards the bottom of contract

### ISSUE THREAD

**Issue by vvillbiii** [Encode-Practice/11-Lottery#4]
https://github.com/Encode-Practice/11-Lottery/blob/4394c9e7b218dd646f2607bbe63f0d5927a43838/Project/contracts/Lottery.sol#L55

I went over the Solidity style guide, and it said that internal functions should be placed towards the bottom of the contract.

**Comment by vvillbiii** [comment]
I might be wrong.

**Comment by bayesdj** [comment]
Lets assume you are correct, Will. The way to address this is by creating a branch from main, address the issue, and create a pull-request. Wanna give it a try?
